apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-holy-sawfish
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "1083466637343"
    project: learnlead-357405
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: leaddevops
    repository: jx3-cluster-repo
  - key: staging
  - key: production
  ingress:
    domain: 35.193.36.161.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: leaddevops
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-holy-sawfish-fe8f20b831f2
  - name: reports
    url: gs://reports-tf-jx-holy-sawfish-fe8f20b831f2
  - name: repository
    url: gs://repository-tf-jx-holy-sawfish-fe8f20b831f2
  terraformVault: true
  vault:
    bucket: vault-tf-jx-holy-sawfish-fe8f20b831f2
    key: crypto-key-tf-jx-holy-sawfish-fe8f20b831f2
    keyring: keyring-tf-jx-holy-sawfish-fe8f20b831f2
    name: tf-jx-holy-sawfish
    serviceAccount: tf-jx-holy-sawfish-vt
  webhook: lighthouse
